version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.78.0
    - 1.88.0
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: i18n-js
    versions:
    - 3.7.1
    - 3.8.0
    - 3.8.1
  - dependency-name: parallel_tests
    versions:
    - 3.1.0
    - 3.4.0
    - 3.5.0
    - 3.5.2
    - 3.6.0
  - dependency-name: devise_masquerade
    versions:
    - 1.2.0
    - 1.3.1
    - 1.3.2
    - 1.3.3
    - 1.3.5
    - 1.3.6
  - dependency-name: autoprefixer-rails
    versions:
    - 9.8.6.1
  - dependency-name: json
    versions:
    - 2.3.1
  - dependency-name: cancancan
    versions:
    - 3.1.0
  - dependency-name: omniauth
    versions:
    - 1.9.1
  - dependency-name: puma
    versions:
    - 4.3.3
  - dependency-name: carrierwave
    versions:
    - 2.1.0
