inherit_from:
  - .rubocop.unhound.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/seeds.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/bundle/**/*"
    - "client/**/*"
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  CountAsOne: ["array", "hash", "heredoc"]

Style/AsciiComments:
  AllowedChars: ["©", "├", "─", "└"]

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/LambdaCall:
  Exclude:
    - "**/*.json.jbuilder"

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/WordArray:
  Enabled: false
