AllCops:
  RunRailsCops: true
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'

LineLength:
  Enabled: false

Documentation:
  Enabled: false
