inherit_from:
  - .rubocop.unhound.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'db/migrate/*'
   - 'vendor/bundle/**/*'
   - 'client/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/EmptyMethod:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/DotPosition:
  EnforcedStyle: trailing
