scss_files: 'app/**/*.scss'

linters:
  # Unhounding.
  HexLength:
    enabled: true

  StringQuotes:
    style: single_quotes

  # Project-specific options
  HexLength:
    style: long

  IdSelector:
    enabled: false

  LeadingZero:
    style: include_zero

  PlaceholderInExtend:
    enabled: false

  QualifyingElement:
    allow_element_with_class: true

  NestingDepth:
    max_depth: 5

  SelectorDepth:
    max_depth: 5
