# frozen_string_literal: true
module Course::Assessment::Answer::ProgrammingTestCaseHelper
  # Get a hint message. Use the one from test_result if available, else fallback to the one from
  # the test case.
  #
  # @param [Course::Assessment::Question::ProgrammingTestCase] The test case
  # @param [Course::Assessment::Answer::ProgrammingAutoGradingTestResult] The test result
  # @return [String] The hint, or an empty string if there isn't one
  def get_hint(test_case, test_case_result)
    hint = test_case_result.messages['hint'] if test_case_result
    hint ||= test_case.hint
    hint || ''
  end

  # Get the output message for the tutors to see when grading. Use the output meta attribute if
  # available, else fallback to the failure message, error message, and finally empty string.
  #
  # @param [Course::Assessment::Answer::ProgrammingAutoGradingTestResult] The test result
  # @return [String] The output, failure message, error message or empty string
  #   if the previous 3 don't exist.
  def get_output(test_case_result)
    if test_case_result
      output = test_case_result.messages['output']
      # The "failure message" in this context comes from the XML generated by default evaluator.
      output = test_case_result.messages['failure'] if output.blank?
      output = test_case_result.messages['error'] if output.blank?
    end
    output || ''
  end

  # Organize the results of a grading run by test case type, keyed by the id of the test case each
  # result is for.
  #
  # Joining on test case id rather than on the test case record itself means the definitions and the
  # results can be serialized separately: a test case belongs to the question, a result belongs to
  # one grading run, and the client re-joins them by id.
  #
  # A test case with no result is omitted -- it was added to the question after this run, so there
  # is nothing to report for it. Where a run somehow holds more than one result for a test case, the
  # first is kept.
  #
  # e.g. { 'public_test' => { 12 => result_12, 13 => result_13 },
  #        'private_test' => { 14 => result_14 } }
  #
  # @param [Hash] test_cases_by_type The test cases keyed by type
  # @param [Course::Assessment::Answer::ProgrammingAutoGrading, nil] auto_grading Auto grading object
  # @return [Hash] The hash structure described above
  def get_test_results_by_type(test_cases_by_type, auto_grading)
    results_by_test_case_id =
      auto_grading ? auto_grading.test_results.group_by(&:test_case_id).transform_values(&:first) : {}

    test_cases_by_type.transform_values do |test_cases|
      test_cases.filter_map do |test_case|
        result = results_by_test_case_id[test_case.id]
        [test_case.id, result] if result
      end.to_h
    end
  end

  # If the test case type has a failed test case, return the first one with its result.
  #
  # A test case with no result has not been run, and is not a failure.
  #
  # @param [Hash] test_cases_by_type The test cases keyed by type
  # @param [Hash] test_results_by_type The results, as returned by +get_test_results_by_type+
  # @return [Hash] Each type maps to a [test_case, test_result] pair, or nil if none failed
  def get_first_failure_by_type(test_cases_by_type, test_results_by_type)
    test_cases_by_type.to_h do |test_case_type, test_cases|
      results = test_results_by_type[test_case_type] || {}
      failed_test_case = test_cases.find { |test_case| results[test_case.id]&.passed? == false }

      [test_case_type, failed_test_case && [failed_test_case, results[failed_test_case.id]]]
    end
  end
end
