# frozen_string_literal: true
module Course::Assessment::Answer::ProgrammingTestCaseHelper
  # Get a hint message. Use the one from test_result if available, else fallback to the one from
  # the test case.
  #
  # @param [Course::Assessment::Question::ProgrammingTestCase] The test case
  # @param [Course::Assessment::Answer::ProgrammingAutoGradingTestResult] The test result
  # @return [String] The hint, or an empty string if there isn't one
  def get_hint(test_case, test_case_result)
    hint = test_case_result.messages['hint'] if test_case_result
    hint ||= test_case.hint
    hint || ''
  end

  # Get the output message for the tutors to see when grading. Use the output meta attribute if
  # available, else fallback to the failure message, error message, and finally empty string.
  #
  # @param [Course::Assessment::Answer::ProgrammingAutoGradingTestResult] The test result
  # @return [String] The output, failure message, error message or empty string
  #   if the previous 3 don't exist.
  def get_output(test_case_result)
    if test_case_result
      output = test_case_result.messages['output']
      # The "failure message" in this context comes from the XML generated by default evaluator.
      output = test_case_result.messages['failure'] if output.blank?
      output = test_case_result.messages['error'] if output.blank?
    end
    output || ''
  end

  # Organize the results of a grading run by test case type, keyed by the id of the test case each
  # result is for.
  #
  # Joining on test case id rather than on the test case record itself means the definitions and the
  # results can be serialized separately: a test case belongs to the question, a result belongs to
  # one grading run, and the client re-joins them by id.
  #
  # A test case with no result is omitted -- it was added to the question after this run, so there
  # is nothing to report for it. Where a run somehow holds more than one result for a test case, the
  # first is kept.
  #
  # e.g. { 'public_test' => { 12 => result_12, 13 => result_13 },
  #        'private_test' => { 14 => result_14 } }
  #
  # @param [Hash] test_cases_by_type The test cases keyed by type
  # @param [Course::Assessment::Answer::ProgrammingAutoGrading, nil] auto_grading Auto grading object
  # @return [Hash] The hash structure described above
  def get_test_results_by_type(test_cases_by_type, auto_grading)
    results_by_test_case_id =
      auto_grading ? auto_grading.test_results.group_by(&:test_case_id).transform_values(&:first) : {}

    test_cases_by_type.transform_values do |test_cases|
      test_cases.filter_map do |test_case|
        result = results_by_test_case_id[test_case.id]
        [test_case.id, result] if result
      end.to_h
    end
  end

  # If the test case type has a failed test case, return the first one with its result.
  #
  # A test case with no result has not been run, and is not a failure.
  #
  # @param [Hash] test_cases_by_type The test cases keyed by type
  # @param [Hash] test_results_by_type The results, as returned by +get_test_results_by_type+
  # @return [Hash] Each type maps to a [test_case, test_result] pair, or nil if none failed
  def get_first_failure_by_type(test_cases_by_type, test_results_by_type)
    test_cases_by_type.to_h do |test_case_type, test_cases|
      results = test_results_by_type[test_case_type] || {}
      failed_test_case = test_cases.find { |test_case| results[test_case.id]&.passed? == false }

      [test_case_type, failed_test_case && [failed_test_case, results[failed_test_case.id]]]
    end
  end

  # The version of the question whose test cases a grading run's results belong to. An edit that re-imports a
  # question moves its test cases onto a snapshot of the previous version instead of deleting them, so a run's
  # results keep pointing at the test cases they were graded against.
  #
  # @param [Course::Assessment::Question::Programming] question The live question.
  # @param [Course::Assessment::Answer::ProgrammingAutoGrading, nil] auto_grading The grading run, if any.
  # @return [Course::Assessment::Question::Programming] The live question or one of its snapshots. The live
  #   question when there is no run, or when the run's results no longer exist to say which version they belong
  #   to -- destroyed by an edit made before snapshots were kept.
  def graded_question_version(question, auto_grading)
    version_id = graded_question_version_id(auto_grading)
    return question if version_id.nil? || version_id == question.id

    question.snapshots.find_by(id: version_id) || question
  end

  # Whether a grading run was graded against an earlier version of the question than the live one, including a
  # run whose results no longer exist to say which version.
  #
  # @param [Course::Assessment::Question::Programming] question The live question.
  # @param [Course::Assessment::Answer::ProgrammingAutoGrading, nil] auto_grading The grading run, if any.
  def graded_on_previous_version?(question, auto_grading)
    auto_grading.present? && graded_question_version_id(auto_grading) != question.id
  end

  private

  # @return [Integer, nil] The id of the question or snapshot owning the run's test cases, or nil if it has no
  #   results that still point at a test case.
  def graded_question_version_id(auto_grading)
    return nil unless auto_grading

    @graded_question_version_ids ||= {}
    @graded_question_version_ids.fetch(auto_grading.id) do
      @graded_question_version_ids[auto_grading.id] =
        Course::Assessment::Question::ProgrammingTestCase.
        where(id: auto_grading.test_results.select(:test_case_id)).pick(:question_id)
    end
  end
end
