development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: application_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://:<%= Rails.application.credentials.dig(:redis, :password) %>@<%= ENV['REDIS_HOST'] %>:6379
  channel_prefix: application_production
