import mirrorCreator from 'mirror-creator';

const actionTypes = mirrorCreator([
  'SET_NOTIFICATION',
  'SET_ITEM_TYPE_VISIBILITY',
  'LOAD_LESSON_PLAN_REQUEST',
  'LOAD_LESSON_PLAN_SUCCESS',
  'LOAD_LESSON_PLAN_FAILURE',
  'ITEM_UPDATE_REQUEST',
  'ITEM_UPDATE_SUCCESS',
  'ITEM_UPDATE_FAILURE',
  'MILESTONE_UPDATE_REQUEST',
  'MILESTONE_UPDATE_SUCCESS',
  'MILESTONE_UPDATE_FAILURE',
]);

export default actionTypes;
